CREATE TABLE IF NOT EXISTS olivisit.visitors (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organisation_id INTEGER NOT NULL,
    first_name VARCHAR(50) NOT NULL, 
    last_name VARCHAR(100) NOT NULL,
    phone_number VARCHAR(10) NOT NULL,
    email VARCHAR(200) NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP,
    created TIMESTAMP NOT NULL,
    modified TIMESTAMP NOT NULL
);
 
-- Foreign Keys --
ALTER TABLE olivisit.visitors DROP CONSTRAINT IF EXISTS FK_ORGANISATIONS;
ALTER TABLE olivisit.visitors ADD CONSTRAINT FK_ORGANISATIONS FOREIGN KEY (organisation_id) REFERENCES olivisit.organisations(id);

--DROP TABLE IF EXISTS olivisit.visitors;