CREATE TABLE IF NOT EXISTS olivisit.organisations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    code VARCHAR(154) NOT NULL UNIQUE,
    organisation_details TEXT,
    is_disabled BOOLEAN NOT NULL DEFAULT FALSE,
    created TIMESTAMP NOT NULL,
    modified TIMESTAMP NOT NULL
);

--DROP TABLE IF EXISTS olivisit.organisations;