CREATE TABLE IF NOT EXISTS olivisit.houserules (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    rule_description TEXT NOT NULL,
    organisation_id INTEGER NOT NULL,
    expiry_date TIMESTAMP,
    created TIMESTAMP NOT NULL,
    modified TIMESTAMP NOT NULL
);

-- Foreign Keys --
ALTER TABLE olivisit.houserules DROP CONSTRAINT IF EXISTS FK_ORGANISATIONS;
ALTER TABLE olivisit.houserules ADD CONSTRAINT FK_ORGANISATIONS FOREIGN KEY (organisations_id) REFERENCES olivisit.organisations(id);

--DROP TABLE IF EXISTS olivisit.houserules;